[package]
name = "surtur"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.1", features = ["cargo"] }
colored = "2.0.4"
git2 = "0.18.2"
mlua = { version = "0.9.7", features = ["lua54", "vendored"]}
