[package]
name = "surtur"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["cargo"] }
clutils = "0.0.11"
colored = "2.0.4"
git2 = "0.18.2"
rlua = { version = "0.20.0"}
