[package]
name = "surtur"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["cargo"] }
clutils = "0.0.9"
colored = "2.0.4"
git2 = "0.18.2"
rlua = "0.20.0"
strum = { version = "0.26.1", features = ["derive"] }
