[package]
name = "surtur"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.84"
clap = { version = "4.5.4", features = ["cargo"] }
colored = "2.1.0"
git2 = "0.18.3"
mlua = { version = "0.9.8", features = ["lua54", "vendored"]}
